"""
procedural-rocket
Generates a low-poly 3D rocket model in pure Python (no dependencies).

Builds a rocket (body, nose cone, 3 fins) vertex-by-vertex with basic
trigonometry and writes it as rocket.obj — open it in Blender, Windows
3D Viewer, or any online OBJ viewer.

Run:
    python3 rocket.py
"""
import math


SEGMENTS = 12       # sides of the body cylinder
BODY_R = 1.0        # body radius
BODY_H = 4.0        # body height
NOSE_H = 1.6        # nose cone height


def main():
    verts = []      # [(x, y, z), ...]
    faces = []      # [(i, j, k), ...] 1-based indices

    def add_vert(x, y, z):
        verts.append((x, y, z))
        return len(verts)

    def ring(y, r):
        ids = []
        for i in range(SEGMENTS):
            a = 2 * math.pi * i / SEGMENTS
            ids.append(add_vert(r * math.cos(a), y, r * math.sin(a)))
        return ids

    # --- body: cylinder wall ---
    bottom = ring(0.0, BODY_R)
    top = ring(BODY_H, BODY_R)
    for i in range(SEGMENTS):
        j = (i + 1) % SEGMENTS
        faces.append((bottom[i], bottom[j], top[j]))
        faces.append((bottom[i], top[j], top[i]))

    # --- bottom cap (fan) ---
    centre = add_vert(0.0, 0.0, 0.0)
    for i in range(SEGMENTS):
        j = (i + 1) % SEGMENTS
        faces.append((centre, bottom[j], bottom[i]))

    # --- nose cone ---
    apex = add_vert(0.0, BODY_H + NOSE_H, 0.0)
    for i in range(SEGMENTS):
        j = (i + 1) % SEGMENTS
        faces.append((apex, top[i], top[j]))

    # --- 3 fins: flat quads sticking out of the body ---
    for k in range(3):
        a = 2 * math.pi * k / 3
        dx, dz = math.cos(a), math.sin(a)
        p1 = add_vert(dx * BODY_R, 0.2, dz * BODY_R)
        p2 = add_vert(dx * BODY_R, 1.8, dz * BODY_R)
        p3 = add_vert(dx * (BODY_R + 1.1), 0.2, dz * (BODY_R + 1.1))
        faces.append((p1, p2, p3))

    with open("rocket.obj", "w") as f:
        f.write("# low-poly rocket generated by procedural-rocket\n")
        f.write("o Rocket\n")
        for x, y, z in verts:
            f.write(f"v {x:.4f} {y:.4f} {z:.4f}\n")
        for i, j, k in faces:
            f.write(f"f {i} {j} {k}\n")

    print(f"rocket.obj written: {len(verts)} vertices, {len(faces)} faces")
    print("open it in Blender / 3D Viewer / https://3dviewer.net")


if __name__ == "__main__":
    main()
